SELECT COUNTRY_NAME, REGION_NAME
FROM HR.COUNTRIES A, HR.REGIONS B
WHERE B.REGION_ID = A.REGION_ID AND B.REGION_ID < 3;

SELECT COUNTRY_NAME, REGION_NAME
FROM HR.REGIONS A, HR.COUNTRIES B
WHERE A.REGION_ID = B.REGION_ID AND B.COUNTRY_NAME LIKE'E%';

SELECT COUNTRY_NAME, REGION_NAME
FROM HR.REGIONS A NATURAL JOIN HR.COUNTRIES B
WHERE B.COUNTRY_NAME LIKE'E%';

SELECT EMPLOYEE_ID, JOB_ID, DEPARTMENT_ID, LAST_NAME, HIRE_DATE, END_DATE
FROM HR.EMPLOYEES A NATURAL JOIN HR.JOB_HISTORY B;

SELECT A.EMPLOYEE_ID, A.JOB_ID, A.DEPARTMENT_ID, LAST_NAME, HIRE_DATE, END_DATE
FROM HR.EMPLOYEES A, HR.JOB_HISTORY B
WHERE A.EMPLOYEE_ID = B.EMPLOYEE_ID;

SELECT EMPLOYEE_ID, JOB_ID, A.DEPARTMENT_ID, LAST_NAME, HIRE_DATE, END_DATE
FROM HR.EMPLOYEES A JOIN HR.JOB_HISTORY B USING(JOB_ID, EMPLOYEE_ID);

SELECT * 
FROM HR.JOBS A JOIN HR.COUNTRIES B USING (A.JOB_ID);


SELECT FIRST_NAME||' '||LAST_NAME||' is manager of the '||DEPARTMENT_NAME AS Managers
FROM HR.DEPARTMENTS A JOIN HR.EMPLOYEES B ON(B.EMPLOYEE_ID=A.MANAGER_ID);

SELECT FIRST_NAME||' '||LAST_NAME||' is manager of the '||DEPARTMENT_NAME AS Managers
FROM HR.DEPARTMENTS A, HR.EMPLOYEES B 
WHERE B.EMPLOYEE_ID=A.MANAGER_ID;

SELECT * FROM HR.DEPARTMENTS;

SELECT A.FIRST_NAME, B.DEPARTMENT_NAME 
FROM HR.EMPLOYEES A, HR.DEPARTMENTS B
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID
ORDER BY 1;

SELECT A.FIRST_NAME, B.DEPARTMENT_NAME
FROM HR.EMPLOYEES A
LEFT OUTER JOIN HR.DEPARTMENTS B
ON(A.DEPARTMENT_ID = B.DEPARTMENT_ID)
ORDER BY 1;

SELECT A.FIRST_NAME, B.DEPARTMENT_NAME
FROM HR.EMPLOYEES A
RIGHT OUTER JOIN HR.DEPARTMENTS B
ON(A.DEPARTMENT_ID = B.DEPARTMENT_ID)
ORDER BY 1;

SELECT A.FIRST_NAME, B.DEPARTMENT_NAME
FROM HR.EMPLOYEES A
FULL OUTER JOIN HR.DEPARTMENTS B
ON(A.DEPARTMENT_ID = B.DEPARTMENT_ID)
ORDER BY 1;

SELECT A.LAST_NAME, A.SALARY, B.DEPARTMENT_NAME, C.CITY, D.COUNTRY_NAME, E.REGION_NAME
FROM HR.EMPLOYEES A, HR.DEPARTMENTS B, HR.LOCATIONS C, HR.COUNTRIES D, HR.REGIONS E
WHERE A.DEPARTMENT_ID = B.DEPARTMENT_ID AND B.LOCATION_ID = C.LOCATION_ID AND C.COUNTRY_ID = D.COUNTRY_ID AND D.REGION_ID = E.REGION_ID AND A.SALARY > 12000;

SELECT A.LAST_NAME, A.SALARY, A.JOB_ID, B.JOB_ID, B.MAX_SALARY
FROM HR.EMPLOYEES A, HR.JOBS B
WHERE B.MAX_SALARY >= 2*A.SALARY AND A.SALARY > 5000
ORDER BY 1;







